version: '3.4'

services:
    api:
        image: nikmsn/api:dev
        build:  
            context: ../Back/
            dockerfile: API/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=443
            - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/certs/API.pfx
        ports:
            - "5000:80"
            - "5001:443"
        volumes:
            - ${PFX_PATH}:/etc/certs/API.pfx:ro
    front:
        image: nikmsn/front:dev
        build:
            context: ../Front/
            dockerfile: Dockerfile
            args: 
                - REACT_APP_MAIN_API_URL=${REACT_APP_MAIN_API_URL}
        environment: 
            - REACT_APP_MAIN_API_URL=$REACT_APP_MAIN_API_URL
        ports:
            - "3000:3000"
    postgres:
        image: postgres
        restart: always
        container_name: Postgres
        environment: 
                - DATABASE_HOST=$DATABASE_HOST
                - POSTGRES_USER=$POSTGRES_USER  
                - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
                - POSTGRES_DB=$POSTGRES_DB  
        ports: 
            - "5432:5432"
